// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSfWcTYEmbewMJIsWLXXZbxDcpD0mmI2w',
    appId: '1:106094078187:web:69d86722ea9708532df6ae',
    messagingSenderId: '106094078187',
    projectId: 'neuro-task-mosaic-5da65',
    authDomain: 'neuro-task-mosaic-5da65.firebaseapp.com',
    storageBucket: 'neuro-task-mosaic-5da65.appspot.com',
    measurementId: 'G-RR4WYP01MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP1zkzUd6D5FfJD5LL3sy53YzJQB8SzME',
    appId: '1:106094078187:android:cfdbb41766eb9d652df6ae',
    messagingSenderId: '106094078187',
    projectId: 'neuro-task-mosaic-5da65',
    storageBucket: 'neuro-task-mosaic-5da65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUu6g7X7PSlxoVQ-_f3ioIviCOIJ6_5P8',
    appId: '1:106094078187:ios:2c6cb9e72a4a8d002df6ae',
    messagingSenderId: '106094078187',
    projectId: 'neuro-task-mosaic-5da65',
    storageBucket: 'neuro-task-mosaic-5da65.appspot.com',
    iosBundleId: 'com.example.neuroTaskMosaic',
  );
}
